module Ppl
  module Product
    PPL_PARCEL_CZ_BUSINESS = 1
    PPL_PARCEL_CZ_BUSINESS_COD = 2
    PPL_PARCEL_CZ_AFTERNOON_PACKAGE = 7
    PPL_PARCEL_CZ_AFTERNOON_PACKAGE_COD = 8
    EXPORT_PACKAGE = 9
    EXPORT_PACKAGE_COD = 10
    PPL_PARCEL_IMPORT = 11
    PPL_PARCEL_CZ_PRIVATE = 13
    PPL_PARCEL_CZ_PRIVATE_COD = 14
    COMPANY_PALETTE = 15
    COMPANY_PALETTE_COD = 16
    PRIVATE_PALETTE = 19
    PRIVATE_PALETTE_COD = 20
    PPL_PARCEL_CONNECT = 36
    PPL_PARCEL_CONNECT_COD = 37

    LIST = [
      self::PPL_PARCEL_CZ_BUSINESS,
      self::PPL_PARCEL_CZ_BUSINESS_COD,
      self::PPL_PARCEL_CZ_AFTERNOON_PACKAGE,
      self::PPL_PARCEL_CZ_AFTERNOON_PACKAGE_COD,
      self::EXPORT_PACKAGE,
      self::EXPORT_PACKAGE_COD,
      self::PPL_PARCEL_CZ_PRIVATE,
      self::PPL_PARCEL_CZ_PRIVATE_COD,
      self::COMPANY_PALETTE,
      self::COMPANY_PALETTE_COD,
      self::PRIVATE_PALETTE,
      self::PRIVATE_PALETTE_COD,
      self::PPL_PARCEL_CONNECT,
      self::PPL_PARCEL_CONNECT_COD
    ].freeze

    CASH_ON_DELIVERY = [
      self::PPL_PARCEL_CZ_BUSINESS_COD,
      self::PPL_PARCEL_CZ_AFTERNOON_PACKAGE_COD,
      self::EXPORT_PACKAGE_COD,
      self::PPL_PARCEL_CZ_PRIVATE_COD,
      self::COMPANY_PALETTE_COD,
      self::PRIVATE_PALETTE_COD,
      self::PPL_PARCEL_CONNECT_COD
    ].freeze

    DELIVERY_SATURDAY = [
      self::PPL_PARCEL_CZ_BUSINESS,
      self::PPL_PARCEL_CZ_BUSINESS_COD,
      self::PPL_PARCEL_CZ_PRIVATE,
      self::PPL_PARCEL_CZ_PRIVATE_COD,
      self::PPL_PARCEL_CZ_AFTERNOON_PACKAGE,
      self::PPL_PARCEL_CZ_AFTERNOON_PACKAGE_COD,
      self::EXPORT_PACKAGE,
      self::EXPORT_PACKAGE_COD
    ].freeze

    PRIVATE_PRODUCTS = [
      self::PPL_PARCEL_CZ_PRIVATE,
      self::PPL_PARCEL_CZ_PRIVATE_COD,
      self::PPL_PARCEL_CZ_AFTERNOON_PACKAGE,
      self::PPL_PARCEL_CZ_AFTERNOON_PACKAGE_COD
    ].freeze
  end
end
